In [6]:
# Q0
print("hello world")

hello world


In [1]:
# Q1
import numpy as np

In [ ]:
#Q2
print(np.__version__)
np.show_config()

In [25]:
#Q3
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
#Q4
Z=np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [26]:
#Q5
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [27]:
#Q6
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [28]:
#Q7
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [29]:
#Q8
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [32]:
#Q9
Z = np.arange(9).reshape(3,3)
Z = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
#Q10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [39]:
#Q11
Z =np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
#Q12
Z = np.random.random((3,3,3))
print(Z)

[[[0.24560611 0.78313281 0.75620382]
  [0.96409043 0.54448177 0.73604808]
  [0.69246353 0.83322787 0.54626505]]

 [[0.23486522 0.75939412 0.97813296]
  [0.03078666 0.53895891 0.92552053]
  [0.50105933 0.40680249 0.38710814]]

 [[0.93267099 0.81176409 0.70923906]
  [0.76563777 0.9851468  0.54861143]
  [0.81722347 0.69665558 0.91440507]]]


In [42]:
#Q13
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

0.009099988263006176 0.9999099982625334


In [43]:
#Q14
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5801557241915339


In [58]:
#Q15
Z = np.ones((10,10))
Z[1:-1,1:-1]=0

Z1 = np.zeros((8,8))
# print(np.info(np.pad))
Z1=np.pad(Z1,1,"constant",constant_values=1)
print(Z)
print(Z1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [60]:
#Q16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#Q17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


In [ ]:
# Q18
Z = np.diag(1+np.arange(4),k=-1)
print(Z)



In [ ]:
#Q19
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

In [ ]:
#Q20
print(np.unravel_index(100,(6,7,8)))

In [ ]:
#Q21
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

In [ ]:
# Q22
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

In [ ]:
# Q23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)


In [ ]:
# Q24
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

In [ ]:
#Q25
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

In [ ]:
#Q26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


In [ ]:
#Q27
Z = np.arange(5)
print(Z ** Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


In [ ]:
# Q28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

In [ ]:
# Q29
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

In [ ]:
#Q30

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


In [ ]:
#Q31
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0



In [ ]:
# Q32

np.sqrt(-1) == np.emath.sqrt(-1) 

In [ ]:
#Q33
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))


In [ ]:
#Q34
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


In [ ]:
#Q35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)



In [ ]:
#Q36
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

In [ ]:
#Q37
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

In [ ]:
#Q38
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

In [ ]:
#Q39
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)



In [ ]:
#Q40
Z = np.random.random(10)
Z.sort()
print (Z)

In [ ]:
#Q41
Z = np.arange(10)
np.add.reduce(Z)

In [ ]:
#Q42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)


In [ ]:
#Q43
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

In [ ]:
#Q44
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)



In [ ]:
#Q45
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

In [ ]:
#Q46
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


In [ ]:
#Q47
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

In [ ]:
#Q48
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

In [ ]:
#Q49
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)


In [ ]:
#Q50
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])
