In [2]:
# Q0
print("hello world")

hello world


In [3]:
# Q1
import numpy as np

In [4]:
#Q2
print(np.__version__)
np.show_config()

1.16.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
#Q3
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#Q4
Z=np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [8]:
#Q5
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
#Q6
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#Q7
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#Q8
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
#Q9
Z = np.arange(9).reshape(3,3)
Z = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#Q10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [14]:
#Q11
Z =np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#Q12
Z = np.random.random((3,3,3))
print(Z)

[[[0.78361853 0.49010537 0.20920637]
  [0.45052931 0.59267531 0.26373675]
  [0.23420698 0.03672238 0.81513201]]

 [[0.40597594 0.26378709 0.41530741]
  [0.17027339 0.40850304 0.31191037]
  [0.83371105 0.15633766 0.25971433]]

 [[0.21624951 0.81789508 0.89032534]
  [0.34428721 0.15558592 0.63364814]
  [0.28163788 0.92376958 0.63806689]]]


In [16]:
#Q13
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

0.007751277604935214 0.9927481419307895


In [17]:
#Q14
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4931363612979034


In [41]:
#Q15
Z = np.ones((10,10))
Z[1:-1,1:-1]=0

Z1 = np.zeros((8,8))
# print(np.info(np.pad))
Z1=np.pad(Z1,1,"constant",constant_values=1)
print(Z)
print(Z1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [42]:
#Q16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [43]:
#Q17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3* 0.1)
print(3*.1)
print(2==.2*10)

nan
False
False
nan
False
0.30000000000000004
True


In [44]:
# Q18
Z = np.diag(1+np.arange(4),k=1)
print(Z)


[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [56]:
#Q19
Z = np.zeros((8,8),dtype=np.int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [73]:
#Q20
print(np.unravel_index(100,(6,7,8)))
print(1*8*7+5*8+4)

(1, 5, 4)
100


In [72]:
#Q21
Z = np.tile(np.array([[0,1],[1,0]]), (2,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [74]:
# Q22
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.24101234 0.80900313 0.         0.00982028 0.46296049]
 [0.77183141 0.33254089 0.47012499 0.62219479 0.22548229]
 [0.15556949 0.31288118 0.00776628 0.54291423 0.42151617]
 [0.15125992 0.08307094 0.84318452 0.36970065 0.87772391]
 [1.         0.63206007 0.34148503 0.87841546 0.32705386]]


In [92]:
# Q23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)
print(type(color))
a = np.array([1,2,4]).astype(color)
print(a)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
<class 'numpy.dtype'>
[(1, 1, 1, 1) (2, 2, 2, 2) (4, 4, 4, 4)]


In [93]:
#Q24
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [104]:
#Q25
Z = np.arange(11)
print(Z[3<Z])
print(type((3<Z)))
Z[np.array([1,3,6])]=2
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[ 0  2  2  2 -4 -5  2 -7 -8  9 10]


In [105]:
#Q26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


In [133]:
#Q27
Z = np.arange(5)
print("Z",Z)
print("Z**Z",Z ** Z)
"""
>>x 小数点左移 == /2**x
9>>2=2
"""
print(9>>2)
print(10>>2)
print(2<<Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


Z [0 1 2 3 4]
Z**Z [  1   1   4  27 256]
2
2
[ 2  4  8 16 32]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [135]:
# Q28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/sunyihuan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/Users/sunyihuan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [139]:
# Q29
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-5.41703129 -0.32846212 -4.107701   -2.1268107   3.12648464  0.4350145
 -4.69716362 -5.44216525  8.13328863 -7.46337287]
[-6. -1. -5. -3.  4.  1. -5. -6.  9. -8.]


In [145]:
#Q30

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))



[3 2 4 2 1 5 0 8 3 8]
[7 1 4 7 2 1 3 9 9 3]
[1 2 3 4]


In [154]:
#Q31
defaults = np.seterr()
Z = np.ones(1) / 0
print(Z)
# _ = np.seterr(**defaults)

# with np.errstate(divide='ignore'):
#     Z = np.ones(1) / 0



[inf]


In [158]:
# Q32
np.sqrt(-1) == np.emath.sqrt(-1) 
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


In [165]:
#Q33
print(np.datetime64('today', 'D'))
print(np.timedelta64(1, 'D'))
print(type(np.datetime64('today', 'D')))
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))


2019-08-10
1 days
<class 'numpy.datetime64'>
Yesterday is 2019-08-09
Today is 2019-08-10
Tomorrow is 2019-08-11


In [166]:
#Q34
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [169]:
#Q35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A,B,C)
np.add(A,B,out=B)
print(A,B,C)
np.divide(A,2,out=A)
print(A,B,C)
np.negative(A,out=A)
print(A,B,C)
np.multiply(A,B,out=A)
print(A,B,C)



[1. 1. 1.] [2. 2. 2.] [3. 3. 3.]
[1. 1. 1.] [3. 3. 3.] [3. 3. 3.]
[0.5 0.5 0.5] [3. 3. 3.] [3. 3. 3.]
[-0.5 -0.5 -0.5] [3. 3. 3.] [3. 3. 3.]
[-1.5 -1.5 -1.5] [3. 3. 3.] [3. 3. 3.]


In [176]:
#Q36
Z = np.random.uniform(-10,10,3)
print(Z)
print(Z%1)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print(int(-4.5))
print (np.trunc(Z))

[-7.99154267  5.9180107   8.49057465]
[0.00845733 0.9180107  0.49057465]
[-8.  5.  8.]
[-8.  5.  8.]
[-8.  5.  8.]
[-7  5  8]
-4
[-7.  5.  8.]


In [180]:
#Q37
Z = np.zeros((3,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [187]:
#Q38
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)
print(type(Z))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [196]:
#Q39
Z = np.linspace(0,1,11,endpoint=True)
print (Z)



[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [197]:
#Q40
Z = np.random.random(10)
Z.sort()
print (Z)

[0.32719216 0.47531865 0.48327734 0.53873354 0.54160259 0.57487379
 0.64520303 0.67803426 0.8142183  0.95294923]


In [200]:
#Q41
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


45

In [221]:
#Q42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.isclose(A,B,rtol=1,atol=2)
print(equal)

equal = np.array_equal(A,B)
print(equal)


[0 1 0 0 0] [1 1 1 0 1]
[ True  True  True  True  True]
False


In [224]:
#Q43
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [226]:
#Q44
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)



[0.39575863 0.80230969 0.74731184 0.52830665 0.27650902 0.95507739
 0.69119986 0.67610184 0.15317673 1.06301   ]
[0.68622861 1.25353926 0.49190796 0.33336744 0.63925838 1.38879941
 1.07468643 0.49338377 0.4618742  0.64775126]


In [227]:
#Q45
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.92738825 0.         0.50422336 0.09248992 0.82287032 0.10466922
 0.44408578 0.32279735 0.90206122 0.26715533]


In [234]:
#Q46
Z = np.zeros((6,5), [('x',np.float),('y',np.float)])
print(Z["x"])
print(Z["y"])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,6))
print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[(0.  , 0. ) (0.25, 0. ) (0.5 , 0. ) (0.75, 0. ) (1.  , 0. )]
 [(0.  , 0.2) (0.25, 0.2) (0.5 , 0.2) (0.75, 0.2) (1.  , 0.2)]
 [(0.  , 0.4) (0.25, 0.4) (0.5 , 0.4) (0.75, 0.4) (1.  , 0.4)]
 [(0.  , 0.6) (0.25, 0.6) (0.5 , 0.6) (0.75, 0.6) (1.  , 0.6)]
 [(0.  , 0.8) (0.25, 0.8) (0.5 , 0.8) (0.75, 0.8) (1.  , 0.8)]
 [(0.  , 1. ) (0.25, 1. ) (0.5 , 1. ) (0.75, 1. ) (1.  , 1. )]]


In [241]:
#Q47
X = np.arange(2)
Y = X + 0.5
print(X,Y)
C = 1.0 / np.subtract.outer(X, Y)
print(np.subtract.outer(X, Y))
print(C)
print(np.linalg.det(C))

[0 1] [0.5 1.5]
[[-0.5 -1.5]
 [ 0.5 -0.5]]
[[-2.         -0.66666667]
 [ 2.         -2.        ]]
5.333333333333334


In [250]:
#Q48
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype,"\nmin:",np.iinfo(dtype).min,"\nmax:",np.iinfo(dtype).max,"\n")

for dtype in [np.float32, np.float64,np.half]:
    print(dtype,"\nmin:",np.finfo(dtype).min,"\nmax:",np.finfo(dtype).max,"\neps:",np.finfo(dtype).eps,"\n")


<class 'numpy.int8'> 
min: -128 
max: 127 

<class 'numpy.int32'> 
min: -2147483648 
max: 2147483647 

<class 'numpy.int64'> 
min: -9223372036854775808 
max: 9223372036854775807 

<class 'numpy.float32'> 
min: -3.4028235e+38 
max: 3.4028235e+38 
eps: 1.1920929e-07 

<class 'numpy.float64'> 
min: -1.7976931348623157e+308 
max: 1.7976931348623157e+308 
eps: 2.220446049250313e-16 

<class 'numpy.float16'> 
min: -65500.0 
max: 65500.0 
eps: 0.000977 



In [282]:
#Q49
np.set_printoptions(threshold=1000000)
Z = np.zeros((16,16),dtype=np.int)
print (Z)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [284]:
#Q50
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])


14


In [285]:
#Q51
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [298]:
#Q52
Z = np.random.random((10,2))
# print(Z)
# print(Z[:,0])
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(X)
print(X.T)
print(X-X.T)
print((X-X.T).shape)
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print (D.shape)

[[0.94758677 0.36126411 0.08837229 0.85549862 0.5319214  0.48669953
  0.55046099 0.80991807 0.11485404 0.58256237]]
[[0.94758677]
 [0.36126411]
 [0.08837229]
 [0.85549862]
 [0.5319214 ]
 [0.48669953]
 [0.55046099]
 [0.80991807]
 [0.11485404]
 [0.58256237]]
[[ 0.         -0.58632266 -0.85921448 -0.09208815 -0.41566537 -0.46088724
  -0.39712578 -0.1376687  -0.83273273 -0.3650244 ]
 [ 0.58632266  0.         -0.27289183  0.49423451  0.17065728  0.12543542
   0.18919688  0.44865395 -0.24641007  0.22129826]
 [ 0.85921448  0.27289183  0.          0.76712633  0.44354911  0.39832725
   0.4620887   0.72154578  0.02648176  0.49419009]
 [ 0.09208815 -0.49423451 -0.76712633  0.         -0.32357722 -0.36879909
  -0.30503763 -0.04558055 -0.74064458 -0.27293625]
 [ 0.41566537 -0.17065728 -0.44354911  0.32357722  0.         -0.04522186
   0.01853959  0.27799667 -0.41706736  0.05064097]
 [ 0.46088724 -0.12543542 -0.39832725  0.36879909  0.04522186  0.
   0.06376145  0.32321853 -0.37184549  0.09586284]
 

In [ ]:
#Q53

In [ ]:
#Q54

In [ ]:
#Q55

In [ ]:
#Q56

In [ ]:
#Q57

In [ ]:
#Q58

In [ ]:
#Q59

In [ ]:
#Q60

In [ ]:
#Q61

In [ ]:
#Q62

In [ ]:
#Q63

In [ ]:
#Q64

In [ ]:
#Q65

In [ ]:
#Q66

In [ ]:
#Q67

In [ ]:
#Q68

In [ ]:
#Q69

In [ ]:
#Q70

In [ ]:
#Q71

In [ ]:
#Q72

In [ ]:
#Q73

In [ ]:
#Q74

In [ ]:
#Q75

In [ ]:
#Q76

In [ ]:
#Q77

In [ ]:
#Q78

In [ ]:
#Q79

In [ ]:
#Q80

In [ ]:
#81

In [ ]:
#82

In [ ]:
#83

In [ ]:
#84

In [ ]:
#85

In [ ]:
#86

In [ ]:
#87

In [ ]:
#88

In [ ]:
#89

In [ ]:
#90

In [ ]:
#91

In [ ]:
#92

In [ ]:
#93

In [ ]:
#94

In [ ]:
#95

In [ ]:
#96

In [ ]:
#97

In [ ]:
#98

In [ ]:
#99

In [ ]:
#100