In [57]:
# Q0
# 作业地址：https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc
print("hello world")

hello world


In [4]:
# Q1
import numpy as np

In [4]:
#Q2
print(np.__version__)
np.show_config()

1.16.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
#Q3
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#Q4
Z=np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [8]:
#Q5
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
#Q6
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#Q7
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#Q8
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
#Q9
Z = np.arange(9).reshape(3,3)
Z = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#Q10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [14]:
#Q11
Z =np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#Q12
Z = np.random.random((3,3,3))
print(Z)

[[[0.78361853 0.49010537 0.20920637]
  [0.45052931 0.59267531 0.26373675]
  [0.23420698 0.03672238 0.81513201]]

 [[0.40597594 0.26378709 0.41530741]
  [0.17027339 0.40850304 0.31191037]
  [0.83371105 0.15633766 0.25971433]]

 [[0.21624951 0.81789508 0.89032534]
  [0.34428721 0.15558592 0.63364814]
  [0.28163788 0.92376958 0.63806689]]]


In [16]:
#Q13
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

0.007751277604935214 0.9927481419307895


In [17]:
#Q14
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4931363612979034


In [41]:
#Q15
Z = np.ones((10,10))
Z[1:-1,1:-1]=0

Z1 = np.zeros((8,8))
# print(np.info(np.pad))
Z1=np.pad(Z1,1,"constant",constant_values=1)
print(Z)
print(Z1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [42]:
#Q16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [43]:
#Q17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3* 0.1)
print(3*.1)
print(2==.2*10)

nan
False
False
nan
False
0.30000000000000004
True


In [44]:
# Q18
Z = np.diag(1+np.arange(4),k=1)
print(Z)


[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [56]:
#Q19
Z = np.zeros((8,8),dtype=np.int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [73]:
#Q20
print(np.unravel_index(100,(6,7,8)))
print(1*8*7+5*8+4)

(1, 5, 4)
100


In [72]:
#Q21
Z = np.tile(np.array([[0,1],[1,0]]), (2,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [74]:
# Q22
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.24101234 0.80900313 0.         0.00982028 0.46296049]
 [0.77183141 0.33254089 0.47012499 0.62219479 0.22548229]
 [0.15556949 0.31288118 0.00776628 0.54291423 0.42151617]
 [0.15125992 0.08307094 0.84318452 0.36970065 0.87772391]
 [1.         0.63206007 0.34148503 0.87841546 0.32705386]]


In [92]:
# Q23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)
print(type(color))
a = np.array([1,2,4]).astype(color)
print(a)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
<class 'numpy.dtype'>
[(1, 1, 1, 1) (2, 2, 2, 2) (4, 4, 4, 4)]


In [93]:
#Q24
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [104]:
#Q25
Z = np.arange(11)
print(Z[3<Z])
print(type((3<Z)))
Z[np.array([1,3,6])]=2
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[ 0  2  2  2 -4 -5  2 -7 -8  9 10]


In [105]:
#Q26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


In [133]:
#Q27
Z = np.arange(5)
print("Z",Z)
print("Z**Z",Z ** Z)
"""
>>x 小数点左移 == /2**x
9>>2=2
"""
print(9>>2)
print(10>>2)
print(2<<Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


Z [0 1 2 3 4]
Z**Z [  1   1   4  27 256]
2
2
[ 2  4  8 16 32]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [135]:
# Q28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/sunyihuan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/Users/sunyihuan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [139]:
# Q29
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-5.41703129 -0.32846212 -4.107701   -2.1268107   3.12648464  0.4350145
 -4.69716362 -5.44216525  8.13328863 -7.46337287]
[-6. -1. -5. -3.  4.  1. -5. -6.  9. -8.]


In [145]:
#Q30

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))



[3 2 4 2 1 5 0 8 3 8]
[7 1 4 7 2 1 3 9 9 3]
[1 2 3 4]


In [154]:
#Q31
defaults = np.seterr()
Z = np.ones(1) / 0
print(Z)
# _ = np.seterr(**defaults)

# with np.errstate(divide='ignore'):
#     Z = np.ones(1) / 0



[inf]


In [158]:
# Q32
np.sqrt(-1) == np.emath.sqrt(-1) 
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


In [165]:
#Q33
print(np.datetime64('today', 'D'))
print(np.timedelta64(1, 'D'))
print(type(np.datetime64('today', 'D')))
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))


2019-08-10
1 days
<class 'numpy.datetime64'>
Yesterday is 2019-08-09
Today is 2019-08-10
Tomorrow is 2019-08-11


In [166]:
#Q34
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [169]:
#Q35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A,B,C)
np.add(A,B,out=B)
print(A,B,C)
np.divide(A,2,out=A)
print(A,B,C)
np.negative(A,out=A)
print(A,B,C)
np.multiply(A,B,out=A)
print(A,B,C)



[1. 1. 1.] [2. 2. 2.] [3. 3. 3.]
[1. 1. 1.] [3. 3. 3.] [3. 3. 3.]
[0.5 0.5 0.5] [3. 3. 3.] [3. 3. 3.]
[-0.5 -0.5 -0.5] [3. 3. 3.] [3. 3. 3.]
[-1.5 -1.5 -1.5] [3. 3. 3.] [3. 3. 3.]


In [176]:
#Q36
Z = np.random.uniform(-10,10,3)
print(Z)
print(Z%1)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print(int(-4.5))
print (np.trunc(Z))

[-7.99154267  5.9180107   8.49057465]
[0.00845733 0.9180107  0.49057465]
[-8.  5.  8.]
[-8.  5.  8.]
[-8.  5.  8.]
[-7  5  8]
-4
[-7.  5.  8.]


In [180]:
#Q37
Z = np.zeros((3,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [187]:
#Q38
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)
print(type(Z))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [196]:
#Q39
Z = np.linspace(0,1,11,endpoint=True)
print (Z)



[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [197]:
#Q40
Z = np.random.random(10)
Z.sort()
print (Z)

[0.32719216 0.47531865 0.48327734 0.53873354 0.54160259 0.57487379
 0.64520303 0.67803426 0.8142183  0.95294923]


In [200]:
#Q41
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


45

In [221]:
#Q42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.isclose(A,B,rtol=1,atol=2)
print(equal)

equal = np.array_equal(A,B)
print(equal)


[0 1 0 0 0] [1 1 1 0 1]
[ True  True  True  True  True]
False


In [224]:
#Q43
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [226]:
#Q44
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)



[0.39575863 0.80230969 0.74731184 0.52830665 0.27650902 0.95507739
 0.69119986 0.67610184 0.15317673 1.06301   ]
[0.68622861 1.25353926 0.49190796 0.33336744 0.63925838 1.38879941
 1.07468643 0.49338377 0.4618742  0.64775126]


In [227]:
#Q45
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.92738825 0.         0.50422336 0.09248992 0.82287032 0.10466922
 0.44408578 0.32279735 0.90206122 0.26715533]


In [234]:
#Q46
Z = np.zeros((6,5), [('x',np.float),('y',np.float)])
print(Z["x"])
print(Z["y"])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,6))
print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[(0.  , 0. ) (0.25, 0. ) (0.5 , 0. ) (0.75, 0. ) (1.  , 0. )]
 [(0.  , 0.2) (0.25, 0.2) (0.5 , 0.2) (0.75, 0.2) (1.  , 0.2)]
 [(0.  , 0.4) (0.25, 0.4) (0.5 , 0.4) (0.75, 0.4) (1.  , 0.4)]
 [(0.  , 0.6) (0.25, 0.6) (0.5 , 0.6) (0.75, 0.6) (1.  , 0.6)]
 [(0.  , 0.8) (0.25, 0.8) (0.5 , 0.8) (0.75, 0.8) (1.  , 0.8)]
 [(0.  , 1. ) (0.25, 1. ) (0.5 , 1. ) (0.75, 1. ) (1.  , 1. )]]


In [241]:
#Q47
X = np.arange(2)
Y = X + 0.5
print(X,Y)
C = 1.0 / np.subtract.outer(X, Y)
print(np.subtract.outer(X, Y))
print(C)
print(np.linalg.det(C))

[0 1] [0.5 1.5]
[[-0.5 -1.5]
 [ 0.5 -0.5]]
[[-2.         -0.66666667]
 [ 2.         -2.        ]]
5.333333333333334


In [250]:
#Q48
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype,"\nmin:",np.iinfo(dtype).min,"\nmax:",np.iinfo(dtype).max,"\n")

for dtype in [np.float32, np.float64,np.half]:
    print(dtype,"\nmin:",np.finfo(dtype).min,"\nmax:",np.finfo(dtype).max,"\neps:",np.finfo(dtype).eps,"\n")


<class 'numpy.int8'> 
min: -128 
max: 127 

<class 'numpy.int32'> 
min: -2147483648 
max: 2147483647 

<class 'numpy.int64'> 
min: -9223372036854775808 
max: 9223372036854775807 

<class 'numpy.float32'> 
min: -3.4028235e+38 
max: 3.4028235e+38 
eps: 1.1920929e-07 

<class 'numpy.float64'> 
min: -1.7976931348623157e+308 
max: 1.7976931348623157e+308 
eps: 2.220446049250313e-16 

<class 'numpy.float16'> 
min: -65500.0 
max: 65500.0 
eps: 0.000977 



In [282]:
#Q49
np.set_printoptions(threshold=1000000)
Z = np.zeros((16,16),dtype=np.int)
print (Z)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [284]:
#Q50
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])


14


In [285]:
#Q51
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [17]:
#Q52
Z = np.random.random((3,2))
# print(Z)
# print(Z[:,0])
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(type(X))
X1,Y1 = np.array([Z[:,0]]),np.array([Z[:,1]])
print(X.shape)
print(X1.shape)
print(X.T)
print(X-X.T)
print((X-X.T).shape)
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print (D)


# # 方法2
# # Much faster with scipy
import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

<class 'numpy.ndarray'>
(1, 3)
(1, 3)
[[0.08663211]
 [0.33572343]
 [0.16071492]]
[[ 0.          0.24909132  0.07408281]
 [-0.24909132  0.         -0.17500851]
 [-0.07408281  0.17500851  0.        ]]
(3, 3)
[[0.         0.45319706 0.35923676]
 [0.45319706 0.         0.17709264]
 [0.35923676 0.17709264 0.        ]]
[[0.         0.45319706 0.35923676]
 [0.45319706 0.         0.17709264]
 [0.35923676 0.17709264 0.        ]]


In [35]:
#Q53
Z = np.arange(10, dtype=np.int32)
Z2 = Z.astype(np.float32, copy=False)
print (Z.dtype,Z2.dtype)

int32 float32


In [51]:
#Q54
from io import StringIO
z = StringIO("1, 2, 3, 4, 5 6,  ,  , 7, 8 ,  , 9,10,11")

Z = np.genfromtxt(z)
print(Z)

[nan nan nan nan  5. nan nan nan nan  8. nan nan nan]


In [55]:
#Q55
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
print("-------------")
for index in np.ndindex(Z.shape):
    print (index, Z[index])
d=np.array([[1,2],[3,4]])
print(d[(1,1)])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
-------------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
4


In [56]:
#Q56
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [58]:
#Q57
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [61]:
#Q58
X = np.random.rand(5, 10)
# # Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
# Y = X - X.mean(axis=1).reshape(-1, 1)
# print (Y)


[[-5.05450712e-02 -1.30780065e-01 -4.18598357e-01 -2.40517426e-01
   4.87068338e-02  3.88960890e-01 -4.15503821e-01  4.76520100e-01
   1.24023767e-01  2.17733150e-01]
 [-2.19519977e-01 -1.54955751e-01  2.84676034e-01  3.22979923e-01
  -2.73397112e-01  4.58184795e-01  1.12112041e-01 -3.06757172e-01
   1.23853282e-01 -3.47176065e-01]
 [-4.06138261e-01  3.54249566e-01 -5.91881230e-02  1.36265698e-01
  -1.80732632e-01 -1.61624557e-01 -6.67478633e-02 -4.50814261e-02
   5.54223686e-01 -1.25226087e-01]
 [-4.50816802e-01 -2.16472170e-01  2.47358708e-01  3.75490462e-02
   1.42102805e-01 -1.09633553e-05  3.92768142e-01  3.32571325e-01
  -1.34543104e-01 -3.50506985e-01]
 [ 2.53657300e-01  7.31711099e-03  4.07581642e-01 -2.91718990e-01
  -2.05570206e-01 -2.68614588e-01 -3.40340689e-01  2.72803127e-01
  -7.89923805e-02  2.43877673e-01]]


In [63]:
#Q59
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])


[[6 2 5]
 [7 2 0]
 [4 7 2]]
[[6 2 5]
 [7 2 0]
 [4 7 2]]


In [64]:
#Q60
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


In [65]:
#Q61
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5114468587915406


In [66]:
#Q62
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [67]:
#Q63
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [69]:
#Q64
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[3. 4. 4. 3. 2. 3. 5. 3. 1. 2.]
[5. 7. 7. 5. 3. 5. 9. 5. 1. 3.]


In [70]:
#Q65
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [71]:
#Q66
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [73]:
#Q67
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[64 51 49 41]
 [57 49 43 52]
 [62 50 62 46]]
[[64 51 49 41]
 [57 49 43 52]
 [62 50 62 46]]


In [75]:
#Q68
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.59625728 0.47588487 0.30583843 0.45755103 0.48757587 0.49433669
 0.60130426 0.57063064 0.48472341 0.4647981 ]
0    0.596257
1    0.475885
2    0.305838
3    0.457551
4    0.487576
5    0.494337
6    0.601304
7    0.570631
8    0.484723
9    0.464798
dtype: float64


In [77]:
#Q69
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

# 方法2
# Fast version
np.sum(A * B.T, axis=1)

# 方法3
# Faster version
np.einsum("ij,ji->i", A, B)


array([2.01645254, 0.99788477, 0.51867492, 1.41753186, 2.31218877])

In [78]:
#Q70
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [79]:
#Q71
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [80]:
#Q72
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [81]:
#Q73
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 1, 33) ( 1, 89) ( 2, 65) ( 2, 76) ( 3,  7) ( 3, 15) ( 7, 15) (10, 32)
 (10, 38) (10, 50) (13, 29) (13, 56) (14, 49) (14, 66) (18, 51) (18, 57)
 (26, 65) (26, 84) (29, 56) (32, 38) (33, 89) (40, 62) (49, 66) (50, 50)
 (51, 57) (62, 62) (65, 76) (65, 84)]


In [82]:
#Q74
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [83]:
#Q75
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [84]:
#Q76
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [85]:
#Q77

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.94067025,  0.73131815, -0.17069356,  0.15572683,  0.5377655 ,
        0.75653137, -0.93606221, -0.73484059,  0.67108194, -0.35770572,
        0.58293087, -0.04072722, -0.20685514,  0.23976235, -0.13625164,
        0.14818598,  0.5139869 , -0.86228774, -0.4715303 ,  0.19979007,
       -0.73914884,  0.93838816,  0.96770216, -0.3552208 , -0.10568649,
        0.82112799, -0.8656536 , -0.09692783, -0.85101781,  0.47798628,
       -0.34749207,  0.3361437 , -0.43607307,  0.86098101, -0.40977499,
       -0.62499661, -0.11056076,  0.74377497,  0.46323144,  0.25227387,
       -0.93577375,  0.62680252, -0.68383746,  0.30512979,  0.19316995,
        0.52750399, -0.58285919,  0.25432808,  0.36901242,  0.34361783,
       -0.90954691,  0.90045281, -0.48797653, -0.90015083, -0.03075161,
        0.42856755, -0.90934993,  0.10540814, -0.26994925, -0.06578499,
        0.52559112,  0.45317353, -0.69427594, -0.94855481,  0.90545397,
        0.06997338,  0.53339778,  0.64204712, -0.41046028,  0.76

In [86]:
#Q78
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[13.33548755  0.46564853  5.60397421 12.73961003  8.54945834  9.50938532
  4.65875551  1.23791566  4.55134124  7.33647136]


In [87]:
#Q79
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.58877426  0.87251382  8.23639146 10.26955489  0.97976111  3.13708195
  11.58211435  6.07529475 12.48804836  8.47863955]
 [ 3.75651595  7.79195048  2.29086262  6.5012151   0.39864258  1.03834498
   4.65055749  0.82410204  5.88527154  1.53029685]
 [ 2.78680613  2.59640661  7.22692024  9.99935009  0.05504432  2.74236581
  10.05472705  4.36650896 11.18141125  6.93303064]
 [ 4.89947984 15.82537138  5.59689891  0.73015902  0.55539683  7.23381563
   3.81352444  4.43625988  2.48698096  6.92395994]
 [ 5.68345317  0.19229642  3.75922733  3.46645147  8.53302604  3.37827044
  10.12287499 10.88853265  9.50692725  7.17167739]
 [ 6.33628556  7.73763524  4.19951926  9.16967332  3.11653595  1.54217744
   5.49243135  0.71538809  7.27251768  2.31689247]
 [ 3.83228451 12.5707642   2.83449452  2.45427137  0.14294503  5.31655705
   0.56764555  1.93735912  0.59421341  3.6691704 ]
 [11.59817715 13.60111018  1.61714563  9.45689392  7.88355163  1.36424036
   0.65729088  7.25004428  3.43869164  2.6055538 ]


In [88]:
#Q80
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[6 2 7 5 8 0 4 8 4 8]
 [6 3 1 5 7 2 6 4 4 7]
 [7 4 3 1 1 3 0 4 4 6]
 [6 7 8 9 7 4 9 3 7 2]
 [0 0 0 6 4 3 3 4 2 5]
 [7 7 6 6 2 2 5 3 0 5]
 [2 0 2 5 3 5 4 8 5 1]
 [3 9 7 7 6 0 8 2 6 0]
 [8 1 5 4 2 9 6 2 2 2]
 [3 2 1 5 5 9 2 8 3 2]]
[[0 0 0 0 0]
 [0 6 2 7 5]
 [0 6 3 1 5]
 [0 7 4 3 1]
 [0 6 7 8 9]]


/Users/sunyihuan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [89]:
#81
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [90]:
#82
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [91]:
#83
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

1


In [92]:
#84
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[0 2 4]
   [3 4 0]
   [0 4 2]]

  [[2 4 2]
   [4 0 2]
   [4 2 1]]

  [[4 2 0]
   [0 2 4]
   [2 1 1]]

  [[2 0 1]
   [2 4 2]
   [1 1 4]]

  [[0 1 2]
   [4 2 3]
   [1 4 4]]

  [[1 2 3]
   [2 3 1]
   [4 4 1]]

  [[2 3 1]
   [3 1 4]
   [4 1 3]]

  [[3 1 2]
   [1 4 2]
   [1 3 4]]]


 [[[3 4 0]
   [0 4 2]
   [2 2 4]]

  [[4 0 2]
   [4 2 1]
   [2 4 1]]

  [[0 2 4]
   [2 1 1]
   [4 1 3]]

  [[2 4 2]
   [1 1 4]
   [1 3 1]]

  [[4 2 3]
   [1 4 4]
   [3 1 3]]

  [[2 3 1]
   [4 4 1]
   [1 3 1]]

  [[3 1 4]
   [4 1 3]
   [3 1 1]]

  [[1 4 2]
   [1 3 4]
   [1 1 0]]]


 [[[0 4 2]
   [2 2 4]
   [3 2 0]]

  [[4 2 1]
   [2 4 1]
   [2 0 2]]

  [[2 1 1]
   [4 1 3]
   [0 2 3]]

  [[1 1 4]
   [1 3 1]
   [2 3 4]]

  [[1 4 4]
   [3 1 3]
   [3 4 3]]

  [[4 4 1]
   [1 3 1]
   [4 3 2]]

  [[4 1 3]
   [3 1 1]
   [3 2 4]]

  [[1 3 4]
   [1 1 0]
   [2 4 4]]]


 [[[2 2 4]
   [3 2 0]
   [3 3 3]]

  [[2 4 1]
   [2 0 2]
   [3 3 2]]

  [[4 1 3]
   [0 2 3]
   [3 2 0]]

  [[1 3 1]
   [2 3 4]
   [2 0 0]]

  [[3 1 3]
   

In [93]:
#85
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 8 15  1  9  7]
 [15  2 13 17 10]
 [ 1 13  2 42  5]
 [ 9 17 42  9 14]
 [ 7 10  5 14  5]]


In [97]:
#86
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [98]:
#87
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [99]:
#88
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [100]:
#89
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])
# 方法2
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9995 9996]


In [101]:
#90
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [102]:
#91
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [103]:
#92
x = np.random.rand()
np.power(x,3)
# 方法2
x*x*x
# 方法3
np.einsum('i,i,i->i',x,x,x)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [104]:
#93
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 1 3 4 5 6]


In [105]:
#94
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)
# 方法2
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print (U)

[[3 3 0]
 [4 1 3]
 [4 4 4]
 [2 3 0]
 [4 4 4]
 [0 2 3]
 [2 1 1]
 [1 3 0]
 [4 3 4]
 [0 1 0]]
[[3 3 0]
 [4 1 3]
 [2 3 0]
 [0 2 3]
 [2 1 1]
 [1 3 0]
 [4 3 4]
 [0 1 0]]
[[3 3 0]
 [4 1 3]
 [2 3 0]
 [0 2 3]
 [2 1 1]
 [1 3 0]
 [4 3 4]
 [0 1 0]]


In [106]:
#95
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
# 方法2
print (np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


TypeError: Expected an input array of unsigned byte data type

In [107]:
#96
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [108]:
#97
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum
4.955801397667504
A * B
[0.00686488 0.67759955 0.15532479 0.0556668  0.09850755 0.45600653
 0.48893774 0.08649832 0.38671562 0.14058064]
inner
2.5527024304702475
outer
[[0.00686488 0.01407272 0.01531956 0.00587216 0.01187093 0.00996354
  0.01562728 0.00201409 0.010079   0.0134208 ]
 [0.330543   0.67759955 0.73763467 0.28274344 0.5715834  0.47974318
  0.75245134 0.096978   0.48530262 0.64620973]
 [0.06960292 0.14268311 0.15532479 0.05953769 0.12035914 0.10102021
  0.15844476 0.0204208  0.10219087 0.13607331]
 [0.06507762 0.13340645 0.14522622 0.0556668  0.11253389 0.0944523
  0.14814334 0.01909312 0.09554685 0.12722639]
 [0.05696628 0.11677854 0.12712508 0.04872843 0.09850755 0.08267967
  0.12967861 0.01671334 0.08363779 0.11136877]
 [0.31418845 0.6440734  0.70113811 0.26875391 0.54330269 0.45600653
  0.71522168 0.09217974 0.4612909  0.61423668]
 [0.21478459 0.44029956 0.47930997 0.18372475 0.37141099 0.31173384
  0.48893774 0.06301564 0.31534633 0.41990267]
 [0.29482372 0.60437649 

In [109]:
#98
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [110]:
#99
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [111]:
#100
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.09303191  0.26257178]
